# Generated by Django 3.1.4 on 2020-12-07 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choferes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ci', models.CharField(max_length=11, unique=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chofere', to=settings.AUTH_USER_MODEL, verbose_name='create of user')),
                ('members', models.ManyToManyField(blank=True, db_table='v1_chofer_members', related_name='choferes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Omnibus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('chapa', models.CharField(max_length=7)),
                ('disponible', models.BooleanField(default=True)),
                ('capacidad', models.IntegerField()),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omnibu', to=settings.AUTH_USER_MODEL, verbose_name='create of user')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=5)),
                ('chofer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chofer1', to='v1.choferes')),
                ('chofer2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chofer2', to='v1.choferes')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='create of user')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='v1.destino')),
                ('omnibus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omnibus', to='v1.omnibus')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='v1.destino')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=10)),
                ('cis', models.CharField(max_length=100)),
                ('asientos', models.IntegerField()),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservacion', to=settings.AUTH_USER_MODEL, verbose_name='create of user')),
                ('members', models.ManyToManyField(blank=True, db_table='v1_reservacion_members', related_name='reservaciones_members', to=settings.AUTH_USER_MODEL)),
                ('viajes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to='v1.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='create of user')),
                ('groups', models.ManyToManyField(blank=True, db_table='v1_project_groups', to='auth.Group')),
                ('members', models.ManyToManyField(blank=True, db_table='v1_project_members', related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ManyToManyField(blank=True, db_table='v1_project_permision', to='auth.Permission')),
            ],
        ),
    ]
