# Generated by Django 2.2.17 on 2020-11-25 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choferes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ci', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Omnibus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('chapa', models.CharField(max_length=7)),
                ('disponible', models.BooleanField(default=True)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=5)),
                ('chofer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chofer1', to='v1.Choferes')),
                ('chofer2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chofer2', to='v1.Choferes')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='v1.Destino')),
                ('omnibus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='omnibus', to='v1.Omnibus')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='v1.Destino')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=10)),
                ('cis', models.CharField(max_length=100)),
                ('asientos', models.IntegerField()),
                ('viajes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to='v1.Viaje')),
            ],
        ),
    ]
