# Generated by Django 3.1.4 on 2020-12-03 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora', models.DateTimeField(auto_now=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='create of user')),
                ('groups', models.ManyToManyField(blank=True, db_table='v1_project_groups', to='auth.Group')),
                ('members', models.ManyToManyField(blank=True, db_table='v1_project_members', related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ManyToManyField(blank=True, db_table='v1_project_permision', to='auth.Permission')),
            ],
        ),
    ]
